name: CI & Auto Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  test-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1' 

      - name: Rodar testes
        run: go test ./...

      - name: Definir próximo número de tag
        id: tag
        run: |
          # pega a última tag (ou v0.0.0 se não tiver tag ainda)
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Última tag: $LAST_TAG"

          # remove o 'v' e separa em X.Y.Z
          VERSION=${LAST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          # incrementa PATCH
          PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "Nova tag: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Criar e enviar nova tag
        run: |
          NEW_TAG=${{ steps.tag.outputs.new_tag }}
          echo "Criando tag $NEW_TAG"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
