name: CI & Auto Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          fetch-tags: true

      - name: Garantir fetch de tags
        run: git fetch --tags --force

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Rodar testes
        run: go test ./...

      - name: Definir próxima tag
        id: tag
        run: |
          # pega a MAIOR tag semântica que começa com v
          LAST_TAG=$(git tag --list 'v*' --sort=-v:refname | head -n1)

          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="v0.0.0"
          fi

          echo "Última tag encontrada: $LAST_TAG"

          VERSION=${LAST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "Nova tag: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Criar e enviar nova tag
        run: |
          NEW_TAG=${{ steps.tag.outputs.new_tag }}
          echo "Criando tag $NEW_TAG"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
